name: matrix tests
on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]
jobs:
  python-version-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]
        bitstring-version: ["", 3.0.0]
    uses: ./.github/workflows/test-python-version.yml
